### ISSUE TITLE
Can't reproduce the original results with the example page

### ISSUE THREAD

**Issue by OBrink** [Kohulan/DECIMER-Image-Segmentation#51]
If you have a look into the Jupyter Notebook, the results differ from the results that we originally got. I tried it with different resolutions but the issue remains the same. I am really curious why it is behaving this way. The model is the same, the test page is the same. I will look search for the virtual environment on my old laptop and search for differences between the environment that is built when installing the package and the environment that we originally worked with. I am a bit puzzled about this.

**Comment by Kohulan** [comment]
Check tensorflow and keras version. Probably that is the issue?

**Comment by Kohulan** [comment]
@OBrink I think this was fixed?

**Comment by OBrink** [comment]
I don't think so. I tried different tensorflow and keras versions, but the problem remains the same. I am beginning to wonder if we accidentally did that with a different version of the model that was not the final one, but I don't really think so. I guess we can close the issue, but the problem remains mysterious

**Comment by Kohulan** [comment]
If this occurs again we reopen this issue
